name: seurat-env
channels:
  - conda-forge
  - defaults

dependencies:
  - r-base=4.3.*
  - r-seurat=5.*
  - r-tidyverse
  - r-data.table
  - r-xml2
  - r-png
  - r-igraph
  - r-httpuv
  - r-shiny
  - r-rmarkdown
  - r-reticulate

  # system libraries (keep minimal, required for R packages)
  - libxml2
  - libcurl
  - openssl
  - zlib
  - pandoc
